version: '3.7'

services:

  api:
    image: rher92/api
    build:
      context: ./star_wars
      dockerfile: Dockerfile.prod
    entrypoint: ['/usr/src/app/entrypoint.prod.sh']
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles    
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=star_wars.settings
      - POSTGRES_DB_DEV=api_dev
      - POSTGRES_DB_TEST=api_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=api-db
      - POSTGRES_PORT=5432
      - FETCH_PEOPLE_API=https://swapi.dev/api/people/
      - MEMCACHED_API=api-db
      - MEMCACHED_PORT=11211
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DEBUG=False
      - SECRET_KEY='7fp!!r-1h(#w=z9!xjvl#*f&_)au9s99le5p=h*k5j51(z)fr&'
    depends_on:
      - api-db
      - api-cache

  api-db:
    image: rher92/api-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/    
    build:
      context: ./star_wars/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api-cache:
    image: memcached
    ports:
      - 11211
    entrypoint:
      - memcached
      - -m 64

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles 
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:          