# Generated by Django 3.1 on 2020-08-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEvaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True)),
                ('average_rating', models.FloatField()),
                ('max_rating', models.PositiveSmallIntegerField()),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', related_query_name='character', to='api.characterevaluations')),
            ],
        ),
    ]
